<a href="https://colab.research.google.com/github/Sakshi-Prajapati/ML_LABS/blob/main/ML_LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Implement Naive Bayes classifier : Weather Example**

In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast','Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

#creating labelEncoder
#overcast = 0 , rainy =1 ,sunny=2
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)

print("Weather:" ,weather_encoded)
print("Temp:",temp_encoded)
print("Play:",label)

#features weather temp
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)

model=MultinomialNB()
model.fit(features,label)

predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

predicted= model.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)

predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)



Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]
Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))
Predicted Value: [1]
Predicted Value: [1]
Predicted Value: [1]


**2_NB_Classifier_Iris_2Classes**

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()
print(iris)

print("Features: ", iris.feature_names)
print("Labels: ", iris.target_names)
print("\nData shape: ",iris.data.shape)
print("\nTraget shape: ",iris.target.shape)
print("\nData type: ",type(iris.data))


newdata = iris.data[50:,:]
newtarget = iris.target[50:]

print("\nNew Data shape: ",newdata.shape)
#print data(target)shape
print("\nNew Traget shape: ",newtarget.shape)


In [ ]:
from sklearn.model_selection import train_test_split
#split data set into train and test sets

data_train, data_test, target_train, target_test = train_test_split(newdata,
newtarget, test_size = 0.30, random_state = 5)

import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

from sklearn.metrics import confusion_matrix
print("confusion_matrix")
print(confusion_matrix(target_test, target_pred))



from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))


Accuracy: 0.9
confusion_matrix
[[16  1]
 [ 2 11]]
precision: 0.8888888888888888
recall: 0.9411764705882353


**3_NB_Classifier_Iris_3Classes**

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()
# print(iris)

print("Features: ", iris.feature_names)
print("Labels: ", iris.target_names)
iris.data.shape

from sklearn.model_selection import train_test_split
#split data set into train and test sets

data_train, data_test, target_train, target_test = train_test_split(iris.data,iris.target, test_size = 0.30, random_state = 10)

import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

from sklearn.metrics import confusion_matrix
print("confusion_matrix")
print(confusion_matrix(target_test, target_pred))


from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred,average=None)
recall = recall_score(target_test, target_pred,average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))


Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']
Accuracy: 1.0
confusion_matrix
[[14  0  0]
 [ 0 17  0]
 [ 0  0 14]]
precision: [1. 1. 1.]
recall: [1. 1. 1.]


**Task 1**

In [ ]:
# Exercise
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

dataset = pd.read_csv('/content/Dataset3.csv')

data = pd.DataFrame(dataset)
# X = dataSet.drop(columns=['Purchased'])
y = data['Class']
print(y)

x1 = pd.get_dummies(dataset.Outlook)
x2 = pd.get_dummies(dataset.Temp)
x3 = pd.get_dummies(dataset.Wind)
x4 = pd.get_dummies(dataset.Humidity)


print(x4)

# print(x1)

data = pd.concat([x1,x2,x3,x4],axis='columns')

data_train, data_test, target_train, target_test = train_test_split(data,y,test_size = 0.15, random_state = 112)

print(data_train)
print("\ndata_test:",data_test)

gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)
# target_pred = gnb.predict([[0,1,0,0,0,1,1,0,0,0,1]])
# target_pred = gnb.predict([[0,0,1,1,0,0,1,0,1,0,0]])
# O  R  S  C  H  M  F  T  0  1  2
# print(target_pred)


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

print("confusion_matrix")
print(confusion_matrix(target_test, target_pred))

precision = precision_score(target_test, target_pred,average=None)
recall = recall_score(target_test, target_pred,average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))


# print(data)
# dataset.shape

# pd.get_dummies(dataset).shape

# print(dataset)
# #Use One Hot Encoder from scikit learn
# onehotencoder = OneHotEncoder()
# #reshape the 1-D country array to 2-D as fit_transform expects 2-D and finally fit the␣,→object
# x1 = onehotencoder.fit_transform(dataset.Outlook.values.reshape(-1,1)).toarray()
# x2 = onehotencoder.fit_transform(dataset.Temp.values.reshape(-1,1)).toarray()
# x3 = onehotencoder.fit_transform(dataset.Wind.values.reshape(-1,1)).toarray()
# x4 = onehotencoder.fit_transform(dataset.Humidity.values.reshape(-1,1)).toarray()

# print(x1);
# print(x2);
# print(x3);
# print(x4);

# features=tuple(zip(x1,x2,x3,x4))
# print(features)




0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    0
11    1
12    1
13    0
Name: Class, dtype: int64
    0  1  2
0   0  1  0
1   0  0  1
2   0  1  0
3   0  1  0
4   0  1  0
5   1  0  0
6   0  1  0
7   0  1  0
8   1  0  0
9   0  0  1
10  0  0  1
11  1  0  0
12  0  1  0
13  0  1  0
    O  R  S  C  H  M  F  T  0  1  2
9   0  0  1  0  0  1  1  0  0  0  1
6   1  0  0  1  0  0  0  1  0  1  0
0   0  1  0  0  1  0  1  0  0  1  0
12  1  0  0  0  1  0  1  0  0  1  0
5   1  0  0  1  0  0  0  1  1  0  0
13  0  0  1  0  0  1  0  1  0  1  0
1   0  1  0  0  1  0  0  1  0  0  1
10  0  1  0  1  0  0  0  1  0  0  1
8   1  0  0  1  0  0  1  0  1  0  0
11  1  0  0  0  0  1  0  1  1  0  0
4   0  0  1  1  0  0  1  0  0  1  0

data_test:    O  R  S  C  H  M  F  T  0  1  2
3  0  1  0  0  0  1  1  0  0  1  0
7  0  1  0  0  0  1  1  0  0  1  0
2  1  0  0  0  1  0  1  0  0  1  0
Accuracy: 0.6666666666666666
confusion_matrix
[[1 0]
 [1 1]]
precision: [0.5 1. ]
recall: [1.  0.5

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


**Task 2**

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.datasets import load_wine
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn import preprocessing


import pandas as pd

wine = datasets.load_wine()
# print(wine)

x = pd.DataFrame(wine['data'])
print(x)

# y = wine.target
print(y)

print(wine.feature_names)
print(wine.target_names)
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
alcohol_encoded=le.fit_transform(x[0])
malic_acid_encoded=le.fit_transform(x[1])
ash_encoded=le.fit_transform(x[2])
alcalinity_of_ash_encoded=le.fit_transform(x[3])
magnesium_encoded=le.fit_transform(x[4])
total_phenols_encoded=le.fit_transform(x[5])
flavanoids_encoded=le.fit_transform(x[6])
nonflavanoid_phenolsencoded=le.fit_transform(x[7])
proanthocyanins_encoded=le.fit_transform(x[8])
color_intensity_encoded=le.fit_transform(x[9])
hue_encoded=le.fit_transform(x[10])
diluted_wines_encoded=le.fit_transform(x[11])
prolineencoded=le.fit_transform(x[12])

features=tuple(zip(alcohol_encoded,malic_acid_encoded,ash_encoded,alcalinity_of_ash_encoded,magnesium_encoded,total_phenols_encoded,flavanoids_encoded,nonflavanoid_phenolsencoded,proanthocyanins_encoded,color_intensity_encoded,hue_encoded,prolineencoded))


# class0 = le.fit_transform()
# class1 = le.fit_transform(wine.class1)
# class2 = le.fit_transform(wine.class2)

# label=tuple(zip(class0,class1,class2))

# ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


data_train, data_test, target_train, target_test = train_test_split(features,wine.target,test_size = 0.34, random_state = 112)

print("\n\ndata: ",data_train)
print("\ndata_test:",data_test)


gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

print("confusion_matrix")
print(confusion_matrix(target_test, target_pred))

precision = precision_score(target_test, target_pred,average=None)
recall = recall_score(target_test, target_pred,average = None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

        0     1     2     3      4     5     6     7     8      9     10  \
0    14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29   5.64  1.04   
1    13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28   4.38  1.05   
2    13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81   5.68  1.03   
3    14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18   7.80  0.86   
4    13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82   4.32  1.04   
..     ...   ...   ...   ...    ...   ...   ...   ...   ...    ...   ...   
173  13.71  5.65  2.45  20.5   95.0  1.68  0.61  0.52  1.06   7.70  0.64   
174  13.40  3.91  2.48  23.0  102.0  1.80  0.75  0.43  1.41   7.30  0.70   
175  13.27  4.28  2.26  20.0  120.0  1.59  0.69  0.43  1.35  10.20  0.59   
176  13.17  2.59  2.37  20.0  120.0  1.65  0.68  0.53  1.46   9.30  0.60   
177  14.13  4.10  2.74  24.5   96.0  2.05  0.76  0.56  1.35   9.20  0.61   

       11      12  
0    3.92  1065.0  
1    3.40  1050.0  
2    3.17  1185.0  
3    3.