<a href="https://colab.research.google.com/github/Sakshi-Prajapati/ML_LABS/blob/main/ML_LAB4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

Training Data

In [ ]:
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70],], dtype='float32')

outputs = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

Convert inputs and targets to tensors

In [ ]:
input_torch = torch.from_numpy(inputs)
output_torch = torch.from_numpy(outputs)
print("input_torch:", input_torch)
print("output_torch:", output_torch)

input_torch: tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
output_torch: tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


Weights and biases

In [ ]:
rand_weight = torch.rand((1,3), requires_grad = True)
print(rand_weight)

rand_bais = torch.rand((5,1), requires_grad = True)
print(rand_bais)

tensor([[0.0547, 0.8212, 0.3299]], requires_grad=True)
tensor([[0.7202],
        [0.3626],
        [0.1962],
        [0.5864],
        [0.9932]], requires_grad=True)


Define Model

In [ ]:
# from sklearn.linear_model import LinearRegression

# regressor = LinearRegression()
# regressor.fit(input_torch,output_torch)
def model(X):
  return X @ rand_weight.T + rand_bais

Generate predictions

In [ ]:
# output_pred = regressor.predict(input_torch)
# output_pred = torch.from_numpy(output_pred)

output_pred = model(input_torch)
print("output_pred", output_pred)

output_pred tensor([[ 73.9207],
        [ 98.7214],
        [134.1331],
        [ 53.6838],
        [106.6982]], grad_fn=<AddBackward0>)


Compare with targets

In [ ]:
print(output_torch)

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


# Loss Function

MSE Loss

In [ ]:
def MSE(t1, t2):
  diff = t1 - t2
  return torch.sum(diff*diff)/diff.numel()

Compute loss

In [ ]:
loss = MSE(output_pred, output_torch)
print(loss)

tensor(376.3502, grad_fn=<DivBackward0>)


# Compute Gradients

Compute gradient

In [ ]:
loss.backward()

Gradients for weights and bais

In [ ]:
print(rand_weight)
print(rand_weight.grad)

print(rand_bais)
print(rand_bais.grad)

tensor([[0.0547, 0.8212, 0.3299]], requires_grad=True)
tensor([[3089.7446, 2602.1738, 1685.4611]])
tensor([[0.7202],
        [0.3626],
        [0.1962],
        [0.5864],
        [0.9932]], requires_grad=True)
tensor([[ 7.1683],
        [ 7.0886],
        [ 6.0532],
        [12.6735],
        [ 1.4793]])


# Adjust weights and biases using gradient descent

In [ ]:
# Generate predictions
output_pred = model(input_torch)
print("output_pred", output_pred)

# Calculate Loss
loss = MSE(output_pred, output_torch)
print("Loss; ", loss)

# Compute Gradients
loss.backward()

# Adjust weights & reset gradients
with torch.no_grad():
    rand_weight -= rand_weight.grad * 1e-5
    # rand_weight -= rand_weight.grad * 0.0000001
    rand_bais -= rand_bais.grad * 1e-5
    # rand_bais -= rand_bais.grad * 0.0000001
    rand_weight.grad.zero_()
    rand_bais.grad.zero_()

# Calculate loss
output_pred = model(input_torch)
loss = MSE(output_pred, output_torch)
print("Loss; ", loss)
print("output_pred: ", output_pred)
print("Actual: ", output_torch)

output_pred tensor([[140.3525],
        [186.0000],
        [216.9712],
        [136.4146],
        [180.9000]], grad_fn=<AddBackward0>)
Loss;  tensor(9379.5615, grad_fn=<DivBackward0>)
Loss;  tensor(1157.9247, grad_fn=<DivBackward0>)
output_pred:  tensor([[ 85.7331],
        [114.3254],
        [132.9782],
        [ 81.2122],
        [112.6701]], grad_fn=<AddBackward0>)
Actual:  tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


# Train for multiple epochs

In [ ]:
for i in range(100):
    output_pred = model(input_torch)
    loss = MSE(output_pred, output_torch)
    loss.backward()
    with torch.no_grad():
      rand_weight -= rand_weight.grad * 1e-5
      # rand_weight -= rand_weight.grad * 0.0000001
      rand_bais -= rand_bais.grad * 1e-5
      # rand_bais -= rand_bais.grad * 0.0000001
      rand_weight.grad.zero_()
      rand_bais.grad.zero_()

# Calculate loss
output_pred = model(input_torch)
loss = MSE(output_pred, output_torch)
print("Loss: ",loss)

print("output_pred: ", output_pred)
print("output_torch: ", output_torch)

Loss:  tensor(37.9282, grad_fn=<DivBackward0>)
output_pred:  tensor([[ 59.4376],
        [ 82.5888],
        [114.8527],
        [ 32.2078],
        [ 95.6583]], grad_fn=<AddBackward0>)
output_torch:  tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


# Linear Regression Model using PyTorch built-ins

In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch
import torch.nn as nn

Take Inputs and targets

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

# Convert into tensor
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# Dataset and DataLoder

In [ ]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

[tensor([[ 91.,  88.,  64.],
         [102.,  43.,  37.],
         [ 73.,  67.,  43.],
         [ 87., 134.,  58.],
         [ 87., 134.,  58.]]), tensor([[ 81., 101.],
         [ 22.,  37.],
         [ 56.,  70.],
         [119., 133.],
         [119., 133.]])]

# nn.Linear

In [ ]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0447,  0.3476,  0.0277],
        [-0.5276,  0.1781, -0.4661]], requires_grad=True)
Parameter containing:
tensor([ 0.4055, -0.0741], requires_grad=True)


#Optimizer

In [ ]:
# Define optimizer use instead of gradient
opt = torch.optim.SGD(model.parameters(), lr=1e-5)
print(opt)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 1e-05
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


# Loss Function

In [ ]:
# Import nn.functional
import torch.nn.functional as F

# Define loss function
loss_fn = F.mse_loss

loss = loss_fn(model(inputs), targets)
print(loss)

tensor(12728.0439, grad_fn=<MseLossBackward0>)


# Train Model

In [ ]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(inputs), targets))

# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

# Generate predictions
preds = model(inputs)
print("Pred: ",preds)
print("Target: ", targets)

Training loss:  tensor(35.9542, grad_fn=<MseLossBackward0>)
Pred:  tensor([[ 58.3648,  71.3934],
        [ 80.3055,  96.0903],
        [121.6284, 142.3134],
        [ 26.9594,  42.3059],
        [ 95.2235, 108.0204],
        [ 58.3648,  71.3934],
        [ 80.3055,  96.0903],
        [121.6284, 142.3134],
        [ 26.9594,  42.3059],
        [ 95.2235, 108.0204],
        [ 58.3648,  71.3934],
        [ 80.3055,  96.0903],
        [121.6284, 142.3134],
        [ 26.9594,  42.3059],
        [ 95.2235, 108.0204]], grad_fn=<AddmmBackward0>)
Target:  tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

# Generate predictions
preds = model(inputs)
print("Pred: ",preds)

Training loss:  tensor(18.6596, grad_fn=<MseLossBackward0>)
Pred:  tensor([[ 57.4785,  70.6914],
        [ 80.2104,  96.7837],
        [122.1619, 140.4599],
        [ 22.7382,  39.4581],
        [ 97.6016, 110.9904],
        [ 57.4785,  70.6914],
        [ 80.2104,  96.7837],
        [122.1619, 140.4599],
        [ 22.7382,  39.4581],
        [ 97.6016, 110.9904],
        [ 57.4785,  70.6914],
        [ 80.2104,  96.7837],
        [122.1619, 140.4599],
        [ 22.7382,  39.4581],
        [ 97.6016, 110.9904]], grad_fn=<AddmmBackward0>)


In [ ]:
# 1. Estimate the value of model parameters(weights and bias) and MSE Loss after training for 1000 epochs.

for i in range(1000):
    output_pred = model(input_torch)
    loss = MSE(output_pred, output_torch)
    loss.backward()
    with torch.no_grad():
      rand_weight -= rand_weight.grad * 1e-5
      # rand_weight -= rand_weight.grad * 0.0000001
      rand_bais -= rand_bais.grad * 1e-5
      # rand_bais -= rand_bais.grad * 0.0000001
      rand_weight.grad.zero_()
      rand_bais.grad.zero_()

# Calculate loss
output_pred = model(input_torch)
loss = MSE(output_pred, output_torch)
print("rand_weight: ", rand_weight)
print("rand_bias: ", rand_bais)
print("Loss: ",loss)

# print("output_pred: ", output_pred)
# print("output_torch: ", output_torch)

rand_weight:  tensor([[-0.1954,  0.7428,  0.5404]], requires_grad=True)
rand_bias:  tensor([[0.6989],
        [0.4206],
        [0.9784],
        [0.2042],
        [0.0069]], requires_grad=True)
Loss:  tensor(133.6618, grad_fn=<DivBackward0>)


In [ ]:
#4 Graph
import numpy as np
for i in range(100):
    output_pred = model(input_torch)
    loss = MSE(output_pred, output_torch)
    loss.backward()
    with torch.no_grad():
      rand_weight -= rand_weight.grad * 1e-5
      # rand_weight -= rand_weight.grad * 0.0000001
      rand_bais -= rand_bais.grad * 1e-5
      # rand_bais -= rand_bais.grad * 0.0000001
      rand_weight.grad.zero_()
      rand_bais.grad.zero_()

loss1 = MSE(output_pred, output_torch)

for i in range(200):
    output_pred = model(input_torch)
    loss = MSE(output_pred, output_torch)
    loss.backward()
    with torch.no_grad():
      rand_weight -= rand_weight.grad * 1e-5
      # rand_weight -= rand_weight.grad * 0.0000001
      rand_bais -= rand_bais.grad * 1e-5
      # rand_bais -= rand_bais.grad * 0.0000001
      rand_weight.grad.zero_()
      rand_bais.grad.zero_()

loss2 = MSE(output_pred, output_torch)

for i in range(300):
    output_pred = model(input_torch)
    loss = MSE(output_pred, output_torch)
    loss.backward()
    with torch.no_grad():
      rand_weight -= rand_weight.grad * 1e-5
      # rand_weight -= rand_weight.grad * 0.0000001
      rand_bais -= rand_bais.grad * 1e-5
      # rand_bais -= rand_bais.grad * 0.0000001
      rand_weight.grad.zero_()
      rand_bais.grad.zero_()

loss3 = MSE(output_pred, output_torch)

for i in range(400):
    output_pred = model(input_torch)
    loss = MSE(output_pred, output_torch)
    loss.backward()
    with torch.no_grad():
      rand_weight -= rand_weight.grad * 1e-5
      # rand_weight -= rand_weight.grad * 0.0000001
      rand_bais -= rand_bais.grad * 1e-5
      # rand_bais -= rand_bais.grad * 0.0000001
      rand_weight.grad.zero_()
      rand_bais.grad.zero_()

loss4 = MSE(output_pred, output_torch)

for i in range(500):
    output_pred = model(input_torch)
    loss = MSE(output_pred, output_torch)
    loss.backward()
    with torch.no_grad():
      rand_weight -= rand_weight.grad * 1e-5
      # rand_weight -= rand_weight.grad * 0.0000001
      rand_bais -= rand_bais.grad * 1e-5
      # rand_bais -= rand_bais.grad * 0.0000001
      rand_weight.grad.zero_()
      rand_bais.grad.zero_()

loss5 = MSE(output_pred, output_torch)

x = np.array([100,200,300,400,500])
import torch
y = torch.tensor([loss1, loss2, loss3, loss4, loss5])
y = y.numpy()
import matplotlib.pyplot as plt

plt.plot(x, y)
  
plt.xlabel('No of echops')
plt.ylabel('loss')
plt.title('echops vs loss')
plt.show()

In [ ]:
# 5. Use the model to predict crop yield for apples if temperature is 70, Rain is 34 and Humidity is 45.

input = np.array([[70, 34, 45]], dtype='float32')
input = torch.from_numpy(input)

output = model(input)
print("Output: ",output.mean())

Output:  tensor(33.9009, grad_fn=<MeanBackward0>)
